// <auto-generated />
using System;
using BillApp2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillApp2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BillApp2.Models.Bireysel", b =>
                {
                    b.Property<int>("idNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idNum"), 1L, 1);

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNum");

                    b.ToTable("Bireysel", (string)null);
                });

            modelBuilder.Entity("BillApp2.Models.Fatura", b =>
                {
                    b.Property<int?>("faturaNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("faturaNo"), 1L, 1);

                    b.Property<int>("kurumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("sonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("faturaNo");

                    b.HasIndex("kurumId");

                    b.HasIndex("userId");

                    b.ToTable("Fatura");
                });

            modelBuilder.Entity("BillApp2.Models.Kurumsal", b =>
                {
                    b.Property<int>("kurumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kurumId"), 1L, 1);

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kurumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("kurumId");

                    b.ToTable("Kurumsal");
                });

            modelBuilder.Entity("BillApp2.Models.Odeme", b =>
                {
                    b.Property<int>("odemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("odemeId"), 1L, 1);

                    b.Property<int?>("faturaNo")
                        .HasColumnType("int");

                    b.Property<int>("idNum")
                        .HasColumnType("int");

                    b.Property<decimal>("odenenMiktari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("odenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("odemeId");

                    b.HasIndex("faturaNo");

                    b.HasIndex("idNum");

                    b.ToTable("OdenmisFatura");
                });

            modelBuilder.Entity("BillApp2.Models.Fatura", b =>
                {
                    b.HasOne("BillApp2.Models.Kurumsal", "Kurumsal")
                        .WithMany()
                        .HasForeignKey("kurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillApp2.Models.Bireysel", "Bireysel")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bireysel");

                    b.Navigation("Kurumsal");
                });

            modelBuilder.Entity("BillApp2.Models.Odeme", b =>
                {
                    b.HasOne("BillApp2.Models.Fatura", "Fatura")
                        .WithMany()
                        .HasForeignKey("faturaNo");

                    b.HasOne("BillApp2.Models.Bireysel", "Bireysel")
                        .WithMany()
                        .HasForeignKey("idNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bireysel");

                    b.Navigation("Fatura");
                });
#pragma warning restore 612, 618
        }
    }
}
